### ISSUE TITLE
Lineage OS and Magisk continue

### ISSUE THREAD

**Issue by Rihcus** [2shrestha22/example#1]
Hi sorry to bother, saw your post on 
https://github.com/topjohnwu/Magisk/issues/3820#issuecomment-865459140

As your phone doesn't support A/B install after OTA is t available for your device. Only other way is to flash with lineage recovery or TWRP (if your device supports it).

**Comment by 2shrestha22** [comment]
Yes I flashed apk file from TWRP. I have a question. Magisk addon script will be lost after clearing data partition from TWRP?
